In [1]:
import pandas as pd 

In [2]:
df=pd.read_csv('check.csv')
df.head()

amazonpay_recency  amt_cc_txn_m2  cnt_cash_wdls_ratio_c7_p7  \
0          32.768844    16891.04711                   1.275063   
1          32.768844    16891.04711                   1.275063   
2          32.768844    16891.04711                   1.275063   
3          32.768844    16891.04711                   1.275063   
4          32.768844    16891.04711                   1.275063   

   cnt_paytm_ecom_ratio_c30_p30  cnt_postpaid_bill_m3  cnt_postpaid_bill_m4  \
0                       1.14939              1.052381              1.042169   
1                       1.14939              1.000000              1.042169   
2                       1.14939              1.052381              1.042169   
3                       1.14939              1.052381              1.042169   
4                       1.14939              1.052381              1.042169   

   cnt_postpaid_bill_m5  min_amt_topup_ratio_c7_p7  secondary_acc_max_bal_m2  \
0              1.039062                   3.358192               36158.44921   
1              1.039062                   3.358192               36158.44921   
2              1.039062                   3.358192               36158.44921   
3              1.039062                   3.358192               36158.44921   
4              1.039062                   3.358192               36158.44921   

   temp_secondary_acc_cnt_credits_c7  target  
0                           2.028529       0  
1                           2.028529       0  
2                           2.028529       0  
3                           2.028529       0  
4                           2.028529       0

In [3]:
df.shape

(16096, 11)

In [4]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [5]:
scaler=StandardScaler()
scaler.fit(df)

StandardScaler()

In [6]:
df2=pd.DataFrame(scaler.fit_transform(df.loc[:,df.columns!='target']),columns=['amazonpay_recency', 'amt_cc_txn_m2', 'cnt_cash_wdls_ratio_c7_p7',
       'cnt_paytm_ecom_ratio_c30_p30', 'cnt_postpaid_bill_m3',
       'cnt_postpaid_bill_m4', 'cnt_postpaid_bill_m5',
       'min_amt_topup_ratio_c7_p7', 'secondary_acc_max_bal_m2',
       'temp_secondary_acc_cnt_credits_c7'])
target=df['target']
df2=df2.join(target)

In [7]:
df2

amazonpay_recency  amt_cc_txn_m2  cnt_cash_wdls_ratio_c7_p7  \
0          -3.245444e-12   3.031044e-12               8.220189e-11   
1          -3.245444e-12   3.031044e-12               8.220189e-11   
2          -3.245444e-12   3.031044e-12               8.220189e-11   
3          -3.245444e-12   3.031044e-12               8.220189e-11   
4          -3.245444e-12   3.031044e-12               8.220189e-11   
...                  ...            ...                        ...   
16091      -3.245444e-12   3.031044e-12               8.220189e-11   
16092      -3.245444e-12   3.031044e-12               8.220189e-11   
16093      -3.245444e-12   3.031044e-12               8.220189e-11   
16094      -3.245444e-12   3.031044e-12               8.220189e-11   
16095      -3.245444e-12   3.031044e-12               8.220189e-11   

       cnt_paytm_ecom_ratio_c30_p30  cnt_postpaid_bill_m3  \
0                      7.750360e-12         -3.279563e-10   
1                      7.750360e-12         -1.152117e+00   
2                      7.750360e-12         -3.279563e-10   
3                      7.750360e-12         -3.279563e-10   
4                      7.750360e-12         -3.279563e-10   
...                             ...                   ...   
16091                 -1.941179e-01         -3.279563e-10   
16092                  7.750360e-12         -3.279563e-10   
16093                  7.750360e-12         -3.279563e-10   
16094                  7.750360e-12         -3.279563e-10   
16095                  7.750360e-12         -3.279563e-10   

       cnt_postpaid_bill_m4  cnt_postpaid_bill_m5  min_amt_topup_ratio_c7_p7  \
0              2.313705e-10                   0.0               5.675436e-12   
1              2.313705e-10                   0.0               5.675436e-12   
2              2.313705e-10                   0.0               5.675436e-12   
3              2.313705e-10                   0.0               5.675436e-12   
4              2.313705e-10                   0.0               5.675436e-12   
...                     ...                   ...                        ...   
16091          2.313705e-10                   0.0               5.675436e-12   
16092          2.313705e-10                   0.0               5.675436e-12   
16093          2.313705e-10                   0.0               5.675436e-12   
16094          2.313705e-10                   0.0               5.675436e-12   
16095          2.313705e-10                   0.0               5.675436e-12   

       secondary_acc_max_bal_m2  temp_secondary_acc_cnt_credits_c7  target  
0                  9.068602e-12                      -1.540883e-11       0  
1                  9.068602e-12                      -1.540883e-11       0  
2                  9.068602e-12                      -1.540883e-11       0  
3                  9.068602e-12                      -1.540883e-11       0  
4                  9.068602e-12                      -1.540883e-11       0  
...                         ...                                ...     ...  
16091             -4.505691e-01                      -1.540883e-11       0  
16092              9.068602e-12                      -3.743938e-02       0  
16093              9.068602e-12                      -1.540883e-11       0  
16094              9.068602e-12                      -1.540883e-11       0  
16095              9.068602e-12                      -1.349754e+00       0  

[16096 rows x 11 columns]

In [8]:
from sklearn.model_selection import train_test_split
X=df2.drop(labels=['target'], axis=1)
y=df2['target']
# separate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(
    df2.drop(labels=['target'], axis=1),
    df2['target'],
    test_size=0.2,
    random_state=0)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [10]:
log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3)}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [12]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])},
             scoring='f1_macro')

In [13]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[4786    1]
 [  42    0]]
0.9910954648995651
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4787
           1       0.00      0.00      0.00        42

    accuracy                           0.99      4829
   macro avg       0.50      0.50      0.50      4829
weighted avg       0.98      0.99      0.99      4829



In [14]:
from imblearn.ensemble import EasyEnsembleClassifier

In [15]:
easy=EasyEnsembleClassifier()
easy.fit(X_train,y_train)

EasyEnsembleClassifier()

In [16]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[3724 1063]
 [  30   12]]
0.7736591426796439
              precision    recall  f1-score   support

           0       0.99      0.78      0.87      4787
           1       0.01      0.29      0.02        42

    accuracy                           0.77      4829
   macro avg       0.50      0.53      0.45      4829
weighted avg       0.98      0.77      0.86      4829



In [17]:
from collections import Counter
Counter(y_train)

Counter({0: 11178, 1: 89})

In [18]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 11178, 1: 89})
The number of classes after fit Counter({0: 111, 1: 89})


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/imblearn/utils/_validation.py:635: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [19]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [20]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[3239 1548]
 [  30   12]]
0.673224270035204
              precision    recall  f1-score   support

           0       0.99      0.68      0.80      4787
           1       0.01      0.29      0.01        42

    accuracy                           0.67      4829
   macro avg       0.50      0.48      0.41      4829
weighted avg       0.98      0.67      0.80      4829



In [21]:
from imblearn.combine import SMOTETomek

In [22]:
os=SMOTETomek(0.75)
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/imblearn/utils/_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


The number of classes before fit Counter({0: 11178, 1: 89})
The number of classes after fit Counter({0: 10999, 1: 8204})


In [23]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [24]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[4657  130]
 [  42    0]]
0.9643818595982605
              precision    recall  f1-score   support

           0       0.99      0.97      0.98      4787
           1       0.00      0.00      0.00        42

    accuracy                           0.96      4829
   macro avg       0.50      0.49      0.49      4829
weighted avg       0.98      0.96      0.97      4829



In [25]:
from imblearn.over_sampling import RandomOverSampler

In [26]:
os=RandomOverSampler(0.75)
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 11178, 1: 89})
The number of classes after fit Counter({0: 11178, 1: 8383})


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/imblearn/utils/_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [28]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[4517  270]
 [  38    4]]
0.9362186788154897
              precision    recall  f1-score   support

           0       0.99      0.94      0.97      4787
           1       0.01      0.10      0.03        42

    accuracy                           0.94      4829
   macro avg       0.50      0.52      0.50      4829
weighted avg       0.98      0.94      0.96      4829

